# Generated by Django 5.2.7 on 2025-10-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('phone', models.IntegerField(max_length=10, unique=True)),
                ('address', models.TextField()),
                ('id_proof', models.FileField(upload_to='kyc_docs/')),
                ('address_proof', models.FileField(upload_to='kyc_docs/')),
                ('kyc_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
