# Generated by Django 5.2.7 on 2025-10-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banking', '0006_customuser_delete_customer'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_user_groups', related_query_name='custom_user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_permissions', related_query_name='custom_user_permission', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
